### ISSUE TITLE
Won't compile on debian stretch (Kernel 4.8.0-2-amd64) due to inode_change_ok

### ISSUE THREAD

**Issue by victor-vanherpt** [ondr3j/paragon-ufsd#4]
I'm trying to compile on Debian stretch, with kernel 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02).
It seems that inode_change_ok has been deprecated on newer kernels, and now setattr_prepare must be used (it could be that it has been backported in debian to kernel 4.8, as it's a 4.9 change...).

ZFS on linux had the same issue: https://github.com/zfsonlinux/zfs/issues/5454

Error message: 
`/home/victor/Projects/paragon-ufsd//ifslinux/ufsdvfs.c:118:9: note: #pragma message: PAGE_SHIFT=12
 #pragma message "PAGE_SHIFT=" __stringify(PAGE_SHIFT)

/home/victor/Projects/paragon-ufsd//ifslinux/ufsdvfs.c: In function ‘ufsd_setattr’:
**/home/victor/Projects/paragon-ufsd//ifslinux/ufsdvfs.c:4490:9: error: implicit declaration of function ‘inode_change_ok’ [-Werror=implicit-function-declaration]
   err = inode_change_ok( i, attr );
         
`

**Comment by ondr3j** [comment]
Fixed in commit 6d5d0d5070b18200c5e008f2de2ea61824fcb467
